- hosts: compute
  become: true
  tasks:
  - name: CFD Librairies for main applications
    yum:
      name:
        - pax
        - libSM
        - libX11
        - libXext
        - libXt
        - redhat-lsb-core
        - libGLU
        - libXrender.x86_64
        - libXtst.x86_64
        - motif-2.3.4-14.el7_5.x86_64
        - mesa-libGLU-9.0.0-4.el7.x86_64
        - mesa-libGLU
        - mesa-libGL
        - motif
        - axel
        - fontconfig
        - freetype
        - freetype-devel
        - fontconfig-devel
        - libXext
        - libXrender-devel.x86_64
        - libXrender.x86_64
        - mesa-libGL.x86_64
        - tmux
        - htop
        - glibc.i686
        - zlib.i686
      state: present
  - name: Raise memory limits
    lineinfile:
      path: /etc/security/limits.conf
      line: '*            hard   memlock           unlimited'
    lineinfile:
      path: /etc/security/limits.conf
      line: '*            soft   memlock           unlimited'
